version: 2.1

executors:
  main:
    docker:
      - image: cimg/base:stable

jobs:
  setup:
    executor: main
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  run-test:
    executor: main
    steps:
      - attach_workspace:
          at: .
      - run: "./test.sh"
  ensure-all-paths-are-lowercase:
    executor: main
    steps:
      - attach_workspace:
          at: .
      - run: git ls-files "**/*.ts" "**/*.tsx" | ./detect-uppercase.sh

workflows:
  on-push:
    jobs:
      - setup
      - run-test:
          requires:
            - setup
      - ensure-all-paths-are-lowercase:
          requires:
            - run-test
